library(ahp)
ahpFile <- system.file("extdata/custom", "fridge.ahp", package="ahp")
fridgeAhp <- Load(ahpFile)
Calculate(fridgeAhp)
print(fridgeAhp, priority = function(x) x$sparent$priority["total", x$name])
Visualize(fridgeAhp)
Analyze(fridgeAhp)
AnalyzeTable(fridgeAhp)
AnalyzeTable(fridgeAhp, decisionMaker = "Father")
AnalyzeTable(fridgeAhp, decisionMaker = "Mother")
AnalyzeTable(fridgeAhp, decisionMaker = "Child")
